<a href="https://colab.research.google.com/github/Khushibung05/backpropagation/blob/main/backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Neural Network Calculations for a Single Training Record

First, let's define the initial parameters, including the normalized inputs, target output, initial weights, biases, and the learning rate, as provided in the problem description.

In [1]:
# Define the given parameters
# Normalized Inputs for one training record
x = {
    'Pclass': 0.2,
    'Age': 0.24,
    'Fare': 0.80
}

# Target Output
y_target = 1

# Initial Weights (Input Layer -> Hidden Layer)
w_ih = {
    'x1_h1': 0.11, 'x2_h1': 0.14, 'x3_h1': 0.17,
    'x1_h2': 0.21, 'x2_h2': 0.24, 'x3_h2': 0.27
}

# Hidden Layer Biases
b_h = {
    'h1': 0.1,
    'h2': 0.1
}

# Initial Weights (Hidden Layer -> Output Layer)
w_ho = {
    'h1_o1': 0.31,
    'h2_o1': 0.34
}

# Output Bias
b_o = 0.1

# Learning Rate
learning_rate = 0.1

print("Parameters initialized successfully.")

Parameters initialized successfully.


### Task 1: Calculate the net input for Hidden Neurons h1 and h2

In [2]:
import numpy as np

# Net input for h1
net_h1 = (x['Pclass'] * w_ih['x1_h1']) + \
         (x['Age'] * w_ih['x2_h1']) + \
         (x['Fare'] * w_ih['x3_h1']) + \
         b_h['h1']

# Net input for h2
net_h2 = (x['Pclass'] * w_ih['x1_h2']) + \
         (x['Age'] * w_ih['x2_h2']) + \
         (x['Fare'] * w_ih['x3_h2']) + \
         b_h['h2']

print(f"Net input for h1 (net_h1): {net_h1:.4f}")
print(f"Net input for h2 (net_h2): {net_h2:.4f}")

Net input for h1 (net_h1): 0.2916
Net input for h2 (net_h2): 0.4156


### Task 2: Apply sigmoid activation and calculate Output of h1 and h2

In [3]:
# Sigmoid activation function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Output of h1
out_h1 = sigmoid(net_h1)

# Output of h2
out_h2 = sigmoid(net_h2)

print(f"Output of h1 (out_h1): {out_h1:.4f}")
print(f"Output of h2 (out_h2): {out_h2:.4f}")

Output of h1 (out_h1): 0.5724
Output of h2 (out_h2): 0.6024


### Task 3: Calculate Net input at output neuron and Final predicted output

In [4]:
# Net input at output neuron
net_o1 = (out_h1 * w_ho['h1_o1']) + \
         (out_h2 * w_ho['h2_o1']) + \
         b_o

# Final predicted output
y_predicted = sigmoid(net_o1)

print(f"Net input at output neuron (net_o1): {net_o1:.4f}")
print(f"Final predicted output (y_predicted): {y_predicted:.4f}")

Net input at output neuron (net_o1): 0.4823
Final predicted output (y_predicted): 0.6183


### Task 4: Calculate the prediction error using Mean Squared Error (MSE)

In [5]:
# Mean Squared Error
mse = 0.5 * (y_target - y_predicted)**2

print(f"Mean Squared Error (MSE): {mse:.4f}")

Mean Squared Error (MSE): 0.0729


### Task 5: Perform Backpropagation

#### Calculate output layer gradients

In [6]:
# Derivative of sigmoid function
def sigmoid_derivative(z):
    return sigmoid(z) * (1 - sigmoid(z))

# Gradient for output neuron
d_mse_d_y_predicted = -(y_target - y_predicted)
d_y_predicted_d_net_o1 = sigmoid_derivative(net_o1)

# Delta for output layer
delta_o1 = d_mse_d_y_predicted * d_y_predicted_d_net_o1

print(f"Output Layer Delta (delta_o1): {delta_o1:.4f}")

Output Layer Delta (delta_o1): -0.0901


#### Calculate hidden layer gradients

In [7]:
# Gradients for hidden layer neurons
# Delta for h1
d_net_o1_d_out_h1 = w_ho['h1_o1']
d_out_h1_d_net_h1 = sigmoid_derivative(net_h1)
delta_h1 = delta_o1 * d_net_o1_d_out_h1 * d_out_h1_d_net_h1

# Delta for h2
d_net_o1_d_out_h2 = w_ho['h2_o1']
d_out_h2_d_net_h2 = sigmoid_derivative(net_h2)
delta_h2 = delta_o1 * d_net_o1_d_out_h2 * d_out_h2_d_net_h2

print(f"Hidden Layer Delta for h1 (delta_h1): {delta_h1:.4f}")
print(f"Hidden Layer Delta for h2 (delta_h2): {delta_h2:.4f}")

Hidden Layer Delta for h1 (delta_h1): -0.0068
Hidden Layer Delta for h2 (delta_h2): -0.0073


### Task 6: Update weights and biases using Gradient Descent

#### Update Hidden $\rightarrow$ Output weights

In [8]:
# Update w_ho['h1_o1']
d_mse_d_w_h1_o1 = delta_o1 * out_h1
w_ho['h1_o1'] = w_ho['h1_o1'] - (learning_rate * d_mse_d_w_h1_o1)

# Update w_ho['h2_o1']
d_mse_d_w_h2_o1 = delta_o1 * out_h2
w_ho['h2_o1'] = w_ho['h2_o1'] - (learning_rate * d_mse_d_w_h2_o1)

print(f"Updated w_ho['h1_o1']: {w_ho['h1_o1']:.4f}")
print(f"Updated w_ho['h2_o1']: {w_ho['h2_o1']:.4f}")

Updated w_ho['h1_o1']: 0.3152
Updated w_ho['h2_o1']: 0.3454


#### Update Output Bias

In [9]:
# Update b_o
d_mse_d_b_o = delta_o1
b_o = b_o - (learning_rate * d_mse_d_b_o)

print(f"Updated b_o: {b_o:.4f}")

Updated b_o: 0.1090


#### Update Input $\rightarrow$ Hidden weights

In [10]:
# Update w_ih['x1_h1']
d_mse_d_w_x1_h1 = delta_h1 * x['Pclass']
w_ih['x1_h1'] = w_ih['x1_h1'] - (learning_rate * d_mse_d_w_x1_h1)

# Update w_ih['x2_h1']
d_mse_d_w_x2_h1 = delta_h1 * x['Age']
w_ih['x2_h1'] = w_ih['x2_h1'] - (learning_rate * d_mse_d_w_x2_h1)

# Update w_ih['x3_h1']
d_mse_d_w_x3_h1 = delta_h1 * x['Fare']
w_ih['x3_h1'] = w_ih['x3_h1'] - (learning_rate * d_mse_d_w_x3_h1)

# Update w_ih['x1_h2']
d_mse_d_w_x1_h2 = delta_h2 * x['Pclass']
w_ih['x1_h2'] = w_ih['x1_h2'] - (learning_rate * d_mse_d_w_x1_h2)

# Update w_ih['x2_h2']
d_mse_d_w_x2_h2 = delta_h2 * x['Age']
w_ih['x2_h2'] = w_ih['x2_h2'] - (learning_rate * d_mse_d_w_x2_h2)

# Update w_ih['x3_h2']
d_mse_d_w_x3_h2 = delta_h2 * x['Fare']
w_ih['x3_h2'] = w_ih['x3_h2'] - (learning_rate * d_mse_d_w_x3_h2)

print(f"Updated w_ih['x1_h1']: {w_ih['x1_h1']:.4f}")
print(f"Updated w_ih['x2_h1']: {w_ih['x2_h1']:.4f}")
print(f"Updated w_ih['x3_h1']: {w_ih['x3_h1']:.4f}")
print(f"Updated w_ih['x1_h2']: {w_ih['x1_h2']:.4f}")
print(f"Updated w_ih['x2_h2']: {w_ih['x2_h2']:.4f}")
print(f"Updated w_ih['x3_h2']: {w_ih['x3_h2']:.4f}")

Updated w_ih['x1_h1']: 0.1101
Updated w_ih['x2_h1']: 0.1402
Updated w_ih['x3_h1']: 0.1705
Updated w_ih['x1_h2']: 0.2101
Updated w_ih['x2_h2']: 0.2402
Updated w_ih['x3_h2']: 0.2706


#### Update Hidden Layer Biases

In [11]:
# Update b_h['h1']
d_mse_d_b_h1 = delta_h1
b_h['h1'] = b_h['h1'] - (learning_rate * d_mse_d_b_h1)

# Update b_h['h2']
d_mse_d_b_h2 = delta_h2
b_h['h2'] = b_h['h2'] - (learning_rate * d_mse_d_b_h2)

print(f"Updated b_h['h1']: {b_h['h1']:.4f}")
print(f"Updated b_h['h2']: {b_h['h2']:.4f}")

Updated b_h['h1']: 0.1007
Updated b_h['h2']: 0.1007


---

## Dataset Loading and Initial Exploration

Now, let's load the Titanic dataset from your Google Drive. First, I'll mount Google Drive to access the file.

In [15]:
import pandas as pd
from google.colab import drive

# Mount your Google Drive
drive.mount('/content/drive')

# Path to the dataset (update if needed)
path = '/content/drive/My Drive/Colab Notebooks/titanic.csv'

# Importing the dataset
df= pd.read_csv(path)
print(df.head())

Mounted at /content/drive
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   

## Data Preprocessing for Neural Network Training

Before training the neural network, we need to preprocess the data. This involves selecting the relevant features, handling missing values, and normalizing the data using Min-Max Scaling.

In [16]:
# Select relevant features and target
features = ['Pclass', 'Age', 'Fare']
target = 'Survived'

df_nn = df[features + [target]].copy()

# Handle missing values in 'Age' by imputing with the mean
df_nn['Age'].fillna(df_nn['Age'].mean(), inplace=True)

# Handle missing values in 'Fare' (though it's less common, ensure no NaNs)
df_nn['Fare'].fillna(df_nn['Fare'].mean(), inplace=True)

print("Missing values handled.")
print(df_nn.head())

Missing values handled.
   Pclass   Age     Fare  Survived
0       3  22.0   7.2500         0
1       1  38.0  71.2833         1
2       3  26.0   7.9250         1
3       1  35.0  53.1000         1
4       3  35.0   8.0500         0


/tmp/ipykernel_1082/1923366003.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_nn['Age'].fillna(df_nn['Age'].mean(), inplace=True)
/tmp/ipykernel_1082/1923366003.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)

### Min-Max Scaling for Features

Now, we'll normalize the selected features ('Pclass', 'Age', 'Fare') to a range between 0 and 1 using Min-Max Scaling. This helps the neural network converge faster.

In [17]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Apply Min-Max Scaling to the features
df_nn[features] = scaler.fit_transform(df_nn[features])

# Store scaler parameters for later use in deployment
scaler_min_ = scaler.data_min_
scaler_scale_ = scaler.scale_ # data_max_ - data_min_

# Prepare input X and target y
X = df_nn[features].values
y = df_nn[target].values

print("Features normalized and X, y prepared.")
print(f"Scaler parameters stored: min_={scaler_min_}, scale_={scaler_scale_}")
print("First 5 rows of normalized features (X):")
print(X[:5])
print("First 5 target values (y):")
print(y[:5])

Features normalized and X, y prepared.
First 5 rows of normalized features (X):
[[1.         0.27117366 0.01415106]
 [0.         0.4722292  0.13913574]
 [1.         0.32143755 0.01546857]
 [0.         0.43453129 0.1036443 ]
 [1.         0.43453129 0.01571255]]
First 5 target values (y):
[0 1 1 1 0]


## Neural Network Model Definition and Training

We will now define the neural network architecture, re-initialize weights and biases as specified, and then implement a training loop to perform forward propagation, error calculation, backpropagation, and weight updates for each record in the dataset. We'll use the same `sigmoid` and `sigmoid_derivative` functions defined previously.

In [18]:
import numpy as np

# Re-define sigmoid activation function (if not already in scope)
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Re-define sigmoid derivative (if not already in scope)
def sigmoid_derivative(z):
    return sigmoid(z) * (1 - sigmoid(z))

# Initial Weights (Input Layer -> Hidden Layer) - using the same initial values as before
w_ih = {
    'x1_h1': 0.11, 'x2_h1': 0.14, 'x3_h1': 0.17,
    'x1_h2': 0.21, 'x2_h2': 0.24, 'x3_h2': 0.27
}

# Hidden Layer Biases
b_h = {
    'h1': 0.1,
    'h2': 0.1
}

# Initial Weights (Hidden Layer -> Output Layer)
w_ho = {
    'h1_o1': 0.31,
    'h2_o1': 0.34
}

# Output Bias
b_o = 0.1

# Learning Rate
learning_rate = 0.1

print("Neural network parameters re-initialized.")

Neural network parameters re-initialized.


### Training Loop: Forward Propagation, Backpropagation, and Weight Updates

We will now iterate through each record in the preprocessed dataset (`X` and `y`) and perform one step of training (forward pass, backpropagation, and weight updates). This mimics one epoch of training.

In [19]:
all_errors = []
predictions = []

for i in range(len(X)):
    x_record = {
        'Pclass': X[i, 0],
        'Age': X[i, 1],
        'Fare': X[i, 2]
    }
    y_target_record = y[i]

    # --- Forward Propagation (Tasks 1, 2, 3) ---

    # Task 1: Calculate net input for Hidden Neurons
    net_h1 = (x_record['Pclass'] * w_ih['x1_h1']) + \
             (x_record['Age'] * w_ih['x2_h1']) + \
             (x_record['Fare'] * w_ih['x3_h1']) + \
             b_h['h1']

    net_h2 = (x_record['Pclass'] * w_ih['x1_h2']) + \
             (x_record['Age'] * w_ih['x2_h2']) + \
             (x_record['Fare'] * w_ih['x3_h2']) + \
             b_h['h2']

    # Task 2: Apply sigmoid activation and calculate Output of h1, h2
    out_h1 = sigmoid(net_h1)
    out_h2 = sigmoid(net_h2)

    # Task 3: Calculate Net input at output neuron and Final predicted output
    net_o1 = (out_h1 * w_ho['h1_o1']) + \
             (out_h2 * w_ho['h2_o1']) + \
             b_o
    y_predicted = sigmoid(net_o1)
    predictions.append(y_predicted) # Store prediction

    # --- Error Calculation (Task 4) ---
    mse = 0.5 * (y_target_record - y_predicted)**2
    all_errors.append(mse)

    # --- Backpropagation (Task 5) ---

    # Calculate output layer gradients
    d_mse_d_y_predicted = -(y_target_record - y_predicted)
    d_y_predicted_d_net_o1 = sigmoid_derivative(net_o1)
    delta_o1 = d_mse_d_y_predicted * d_y_predicted_d_net_o1

    # Calculate hidden layer gradients
    d_net_o1_d_out_h1 = w_ho['h1_o1']
    d_out_h1_d_net_h1 = sigmoid_derivative(net_h1)
    delta_h1 = delta_o1 * d_net_o1_d_out_h1 * d_out_h1_d_net_h1

    d_net_o1_d_out_h2 = w_ho['h2_o1']
    d_out_h2_d_net_h2 = sigmoid_derivative(net_h2)
    delta_h2 = delta_o1 * d_net_o1_d_out_h2 * d_out_h2_d_net_h2

    # --- Weight Updates (Task 6) ---

    # Update Hidden -> Output weights
    w_ho['h1_o1'] = w_ho['h1_o1'] - (learning_rate * delta_o1 * out_h1)
    w_ho['h2_o1'] = w_ho['h2_o1'] - (learning_rate * delta_o1 * out_h2)

    # Update Output Bias
    b_o = b_o - (learning_rate * delta_o1)

    # Update Input -> Hidden weights
    w_ih['x1_h1'] = w_ih['x1_h1'] - (learning_rate * delta_h1 * x_record['Pclass'])
    w_ih['x2_h1'] = w_ih['x2_h1'] - (learning_rate * delta_h1 * x_record['Age'])
    w_ih['x3_h1'] = w_ih['x3_h1'] - (learning_rate * delta_h1 * x_record['Fare'])

    w_ih['x1_h2'] = w_ih['x1_h2'] - (learning_rate * delta_h2 * x_record['Pclass'])
    w_ih['x2_h2'] = w_ih['x2_h2'] - (learning_rate * delta_h2 * x_record['Age'])
    w_ih['x3_h2'] = w_ih['x3_h2'] - (learning_rate * delta_h2 * x_record['Fare'])

    # Update Hidden Layer Biases
    b_h['h1'] = b_h['h1'] - (learning_rate * delta_h1)
    b_h['h2'] = b_h['h2'] - (learning_rate * delta_h2)

print(f"Training complete for {len(X)} records (one epoch).")
print(f"Average MSE over the dataset: {np.mean(all_errors):.4f}")

Training complete for 891 records (one epoch).
Average MSE over the dataset: 0.1203


## Model Evaluation

After training for one epoch, let's evaluate the model's performance on the training data. We'll convert the predicted probabilities to binary predictions and calculate the accuracy.

In [20]:
from sklearn.metrics import accuracy_score

# Convert predicted probabilities to binary predictions (0 or 1)
binary_predictions = [1 if p >= 0.5 else 0 for p in predictions]

# Calculate accuracy
accuracy = accuracy_score(y, binary_predictions)

print(f"Final Accuracy after one epoch: {accuracy:.4f}")

print("\nFinal Updated Weights and Biases:")
print("Input -> Hidden Weights:", {k: f'{v:.4f}' for k, v in w_ih.items()})
print("Hidden Biases:", {k: f'{v:.4f}' for k, v in b_h.items()})
print("Hidden -> Output Weights:", {k: f'{v:.4f}' for k, v in w_ho.items()})
print("Output Bias:", f'{b_o:.4f}')

Final Accuracy after one epoch: 0.5993

Final Updated Weights and Biases:
Input -> Hidden Weights: {'x1_h1': '0.0856', 'x2_h1': '0.1297', 'x3_h1': '0.1682', 'x1_h2': '0.1840', 'x2_h2': '0.2288', 'x3_h2': '0.2680'}
Hidden Biases: {'h1': '0.0710', 'h2': '0.0687'}
Hidden -> Output Weights: {'h1_o1': '-0.0439', 'h2_o1': '-0.0608'}
Output Bias: -0.4974
